config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> flats out of our <%= Flat.count %> on our website.</p>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="flat-card">
          <div class="flat-card-image"></div>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex">
                <p>Guests: <%= flat.number_of_guests %></p>
              </div>
              <div class="flex ml-3">
                <p><%= flat.price_per_night %> $</p>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to 'More info', flat_path(flat) %>
            <a href="#" class="ml-3 text-warning">Edit</a>
            <a href="#" class="ml-3 text-danger">Remove</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Add new Flat</h1>

<%= form_for [ @flat] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.label :number_of_guests %>
  <%= f.number_field :number_of_guests %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Simple Airbnb', flats_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary my-2 my-sm-0 ml-2' %>
        </div>
      </div>
    </nav>
  <div class="container">
      <%= yield %>
    </div>
  </body>
</html>